# Generated by Django 3.0.4 on 2020-03-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodictask',
            name='client_url_base',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='periodictask',
            name='name',
            field=models.CharField(help_text='Short Description For This Task', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='periodictask',
            name='property_id',
            field=models.IntegerField(null=True),
        ),
    ]
